modLoader = "javafml"
loaderVersion = "[36,)"
license = "AGPL v3.0 License"
issueTrackerURL="https://github.com/chenjj100419/VectorMech/issues"
[[mods]]
modId = "vectormech"
version = "${file.jarVersion}"
displayName = "VectorMech"
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://chenjj100419.github.io/"
logoFile="logo.png"
credits="Mod make -> chenjj100419"
authors = "chenjj100419"
description = '''
Minecraft Technology mod by chenjj100419
'''
[[dependencies.vectormech]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "BOTH"
[[dependencies.vectormech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
